"""empty message

Revision ID: 5e3650081c9b
Revises: 6a6504f17cb3
Create Date: 2024-02-28 18:50:12.945202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e3650081c9b'
down_revision = '6a6504f17cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppies', schema=None) as batch_op:
        batch_op.drop_column('novabreed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('novabreed', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
